### ISSUE TITLE
new rockspec version 0.3.2 and into luarocks repo?

### ISSUE THREAD

**Issue by soumith** [Neopallium/nixio#11]
nixio doesn't build anymore with gcc 4.8.0+ on luarocks's version 0.3.1

A commit was made to fix this in scm over here:
https://github.com/Neopallium/nixio/commit/07f91adaf0768e0ad0831b0ee76f7e7be08471b8

However, in the default luarocks build server, the rockspec is still 0.3.1 with an older version of the source.

It would be great to issue a new version so that nixio build by default in luarocks without having to manually pull the scm rockspec

**Comment by karlp** [comment]
:+1:

**Comment by spiccinini** [comment]
Hi @Neopallium doing GSoC I got into this issue as we need/want to use nixio inside a docker image. Can I help you to do a release and update the luarocks package? Here I did an atempt https://github.com/Neopallium/nixio/pull/17 plase tell me how it looks and what are your plans on this.

(If you are interested in why we are using nixio you can read this blog post https://blog.freifunk.net/2019/07/21/unittesting-libremesh-gsoc-mid-term-update/)

**Comment by karlp** [comment]
FWIW; given how completely stagnant this project appears to be, to simply replace nixio in openwrt with https://github.com/luaposix/luaposix  I've done that in all of my own projects so far, so that my apps run easily on both host/openwrt instead of having to do deal with this.    It's ~straightforward in nearly all locations, and moves sideways to an actively maintained project.

**Comment by Neopallium** [comment]
Fix in release 0.4: `luarocks install Neopallium/nixio`
